//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Razor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaJuntas
    {
        public int Id { get; set; }
        public string Sala { get; set; }
        public string NombreEmpleado { get; set; }
        public System.DateTime FechaRecepcion { get; set; }
        public int TotalPersonas { get; set; }
        public int Horas { get; set; }
    }
}
