//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Razor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoSala
    {
        public int IdTipoSala { get; set; }
        public string TipoSalaJuntas { get; set; }
    }
}
